spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carpro?serverTimezone=GMT%2b8
    username: root
    password: 2333

  # redis相关配置
  redis:
    # 配置主机
    host: 127.0.0.1
    # 配置使用的数据库
    database: 0
    # 指定端口
    port: 6379
